name: We were architects
favicon: null
layout_spectrum: 0.76947
typography_spectrum: 0.69579
title: We were Architects
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-77140863-3
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1d1e20'
    - '#868185'
    - '#4d5760'
    - '#dfddde'
    - '#914a34'
  brandStrength: 0.1875
  lightness: 0.43664384726434946
  saturation: 0.5625
  rhythmicContrast: 0.1850364690180868
purpose: []
