name: We were architects
favicon: null
layout_spectrum: 0.55895
typography_spectrum: 0.69579
title: We were Architects
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-77140863-3
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfcfc'
    - '#f5b09c'
    - '#de796d'
    - '#010002'
    - '#a17570'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.75
  rhythmicContrast: 0
purpose: []
